name: Publish Windows Binaries

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      shell: pwsh
      run: |
        $version = (Select-String -Path Cargo.toml -Pattern '^version =' | ForEach-Object { ($_ -split '"')[1] })
        echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Build
      run: cargo build --release

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/media-sync.exe
        tag_name: v${{ env.version }}